### PR TITLE
Implements VtexId service

### PR DESCRIPTION
**Pull request by gkozlowaski**

### CODE REVIEW

**Comment by brenoc** [comment]
@gkozlowaski I don't know if you done it yet, but I think it could be good to put the set cookie logic here as well. What do you think?

**Comment by brenoc** [comment]
Also, can you rebase it, please? I just merged another branch in master.

**Comment by gkozlowaski** [comment]
@brenoc I've done a login component (https://github.com/vtex-apps/login), that sets the cookie to login and clears it to logout. I think that logic is better inside a component that uses a service from sdk. You think it would be better if that logic was inside sdk?

**Comment by gkozlowaski** [comment]
@brenoc rebased

**Comment by brenoc** [comment]
@gkozlowaski hmmm, I think it's better to just keep it all inside vtex-apps/login, since only this app will use it.

**Comment by brenoc** [comment]
@tamorim what's your opinion?

**Comment by gkozlowaski** [comment]
@brenoc when you say all of it, you are saying the calls to Vtex Id too? I think that keeping that inside sdk makes easier for other developers to make their own login components.

**Comment by brenoc** [comment]
@gkozlowaski I think that will hardly happen. But if you going to that approach, the cookie logic must be inside the service, since you can't login using VTEX ID without properly setting the cookies. 

Do you see what my point is?

There's two approaches:
1. Other developers will develop new login components using VTEX ID: in this case all the API and business logic must be abstracted to the developer, like an SDK. Is a "if all developer must do this, I'll provide the right way to do it" mentality.
2. vtex.login is an app for login using VTEX ID: if other users want to develop other login methods, they should make their own.

**Comment by gkozlowaski** [comment]
@brenoc Yes, makes sense. And you think that the second approach is better? My fear is that in order to change the UI of vtex.login, the dev would have to fork the app and basically rebuild the components inside, wouldn't be easier for him to just create a new one using a logic from the sdk?

**Comment by brenoc** [comment]
@gkozlowaski yep, I think both options are good. If you want to pursue the first, I think you should include the cookies thing, so one shouldn't write the same code again.

**Comment by tamorim** [comment]
@brenoc @gkozlowaski Well,do agencies tend to customize the login component? Do they want?
Since it's a trade off, we should see if it's actually needed.

Sincerely I don't think that will happen often... Maybe put everything inside the login component and on a next interaction decouple the store and actions to be separated apps, this way if someone wants to make their own he doesnt need to do all the heavy work and the SDK keeps from heaving code it doesnt need.

What do you guys think?

**Comment by gkozlowaski** [comment]
@tamorim For me that's good, really liked the idea of separating the apps on a next interaction.

**Comment by brenoc** [comment]
Good! Closing this PR.

**Pull request closed without merging**
