### PR TITLE
Show debug message when route component is not found

### PR DESCRIPTION
**Pull request by brenoc**
From this:
debug-no

To this:
debug-message

### CODE REVIEW

**Comment by dfosco** [comment]
@brenoc Does it makes sense to inform in the example _where_ the component should be registered?

**Comment by brenoc** [comment]
@dfosco What do you mean? Because it really doesn't matter where the component is registered in the code.

Maybe I'll remove this code example and just link to the docs. What do you think?

**Comment by dfosco** [comment]
If it doesn't matter don't worry.

But linking to the docs is a good idea — if the user can't fix the issue
and keeps seeing the error message, it's good to point the way out to the
docs :ok_hand:

2015-11-11 19:45 GMT-02:00 Breno Calazans <notifications@github.com>:

> @dfosco <https://github.com/dfosco> What do you mean? Because it really
> doesn't matter where the component is registered in the code.
>
> Maybe I'll remove this code example and just link to the docs. What do you
> think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex-apps/storefront-sdk/pull/30#issuecomment-155919398>
> .
>



-- 
Daniel Fosco - UX
lab.vtex.com
+55 21 979571497

**Comment by brenoc** [comment]
@tamorim opinions?

**Comment by tamorim** [comment]
@brenoc I like the example! But I think that it should have a link to the docs also.
Big improvement here! :D

**Comment by brenoc** [comment]
O que acham disso? Agora o código procura um componente registrado que seja escrito parecido e sugere que pode ser um typo. Também coloquei o link pro docs.
new-message

**Comment by tamorim** [comment]
@brenoc Nice! Maybe just a little bit of margin after the title? But I'm nitpicking now

**Comment by dfosco** [comment]
Nitpicking about margins? That's my job @tamorim :relieved:

@amoreira suggested that we do an actual template for error messages following a color scheme for each type of error — I'll start looking into it and see if I can get something done this week!

**Comment by brenoc** [comment]
@dfosco feel free to commit your changes in this branch. Do your magic!

**Comment by dfosco** [comment]
@brenoc I added the layout with some mocked variables — if it's an error it will show the `error` badge, but in the future if there are other types of error states that warrant a page like this, we could change the badge text and color.

**Comment by dfosco** [comment]
Here's the baby: 

screen shot 2015-11-13 at 5 10 26 pm

**Comment by brenoc** [comment]
That's awesome! :grin:

**Comment by tamorim** [comment]
@brenoc @dfosco What's missing here? (Besides a rebase)

**Comment by brenoc** [comment]
@tamorim I'll wait for #38

**Comment by tamorim** [comment]
@brenoc It's merged now! :D

**Comment by tamorim** [comment]
@brenoc rock on :zap: :guitar: :zap:

**Pull request merged**
